var html =  '<div class="box">';
    html += '  <table class="upd">';
    html += '    <tr>';
    html += '      <td rowspan="4" class="upd">24/01/20</td>';
    html += '      <td class="upd">行頭のNoをcssでインクリメントに。便利。</td>';
    html += '    </tr>';
    html += '    <tr>';
    html += '      <td class="upd">『愛妻日記』、『環と周』 → 2024年の記録</td>';
    html += '    </tr>';
    html += '    <tr>';
    html += '      <td class="upd">アコーディオン追加（しただけ）</td>';
    html += '    </tr>';
    html += '    <tr>';
    html += '      <td class="upd">ヘッダ（メニュー）・フッタ（ページトップに戻る）追加</td>';
    html += '    </tr>';
    html += '    <tr>';
    html += '      <td class="upd">24/01/18</td>';
    html += '      <td class="upd">ファイト・クラブ ─ 2024年の記録</td>';
    html += '    </tr>';
    html += '    <tr>';
    html += '      <td class="upd">24/01/17</td>';
    html += '      <td class="upd">紙媒体積読状況記載完了</td>';
    html += '    </tr>';
    html += '  </table>';
    html += '</div>';
document.write(html);
