var html =  '<footer>';
    html += '  <nav class="ftr">';
    html += '    <ul>';
    html += '      <li class="first">';
    html += '        <a href="../docs/index.html">積読状況</a>';
    html += '      </li>';
    html += '      <li>';
    html += '        <a href="../docs/before.html">以前</a>';
    html += '      </li>';
    html += '      <li>';
    html += '        <a href="../docs/record_this_month.html">今月</a>';
    html += '      </li>';
    html += '      <li>';
    html += '        <a href="../docs_mypage./mypage.html">mypage</a>';
    html += '      </li>';
    html += '      <li>';
    html += '        <a href="#">▲ UP ▲</a>';
    html += '      </li>';
    html += '  </nav>';
    html += '</footer>';
document.write(html);